import React from 'react';

// const CARD_MOCK = [
//    {
//       id: 1,
//       image: 'string',
//       text: 'string',
//       date: '2021-12-12',
//       lesson_num: 0,
//       title: 'string',
//       author: 0,
//    },
//    {
//       id: 2,
//       image: 'string',
//       text: 'string',
//       date: '2021-12-12',
//       lesson_num: 0,
//       title: 'string',
//       author: 0,
//    },
//    {
//       id: 3,
//       image: 'string',
//       text: 'string',
//       date: '2021-12-12',
//       lesson_num: 0,
//       title: 'string',
//       author: 0,
//    },
//    {
//       id: 4,
//       image: 'string',
//       text: 'string',
//       date: '2021-12-12',
//       lesson_num: 0,
//       title: 'string',
//       author: 0,
//    },
//    {
//       id: 5,
//       image: 'string',
//       text: 'string',
//       date: '2021-12-12',
//       lesson_num: 0,
//       title: 'string',
//       author: 0,
//    },
//    {
//       id: 6,
//       image: 'string',
//       text: 'string',
//       date: '2021-12-12',
//       lesson_num: 0,
//       title: 'string',
//       author: 0,
//    },
//    {
//       id: 7,
//       image: 'string',
//       text: 'string',
//       date: '2021-12-12',
//       lesson_num: 0,
//       title: 'string',
//       author: 0,
//    },
//    {
//       id: 8,
//       image: 'string',
//       text: 'string',
//       date: '2021-12-12',
//       lesson_num: 0,
//       title: 'string',
//       author: 0,
//    },
//    {
//       id: 9,
//       image: 'string',
//       text: 'string',
//       date: '2021-12-12',
//       lesson_num: 0,
//       title: 'string',
//       author: 0,
//    },
//    {
//       id: 10,
//       image: 'string',
//       text: 'string',
//       date: '2021-12-12',
//       lesson_num: 0,
//       title: 'string',
//       author: 0,
//    },
//    {
//       id: 11,
//       image: 'string',
//       text: 'string',
//       date: '2021-12-12',
//       lesson_num: 0,
//       title: 'string',
//       author: 0,
//    },
// ];
